source 'https://rubygems.org'
ruby '2.3.3'

gem 'rails', '~> 5.0.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'

gem 'puma', '3.8.0'
gem 'rack-timeout'

gem 'activemodel-datastore', path: File.expand_path('../../../..', __FILE__)

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
  gem 'better_errors'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'minitest-reporters'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'faker'
  gem 'factory_girl'
end
