AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - "activemodel-datastore.gemspec"
    - "Rakefile"
    - "lib/active_model/datastore/version.rb"
    - "test/support/datastore_example_rails_app/bin/**/*"
    - "test/support/datastore_example_rails_app/config/environments/**/*"
    - "test/support/datastore_example_rails_app/config/application.rb"
    - "test/support/datastore_example_rails_app/config/initializers/backtrace_silencers.rb"
    - "test/support/datastore_example_rails_app/config/initializers/session_store.rb"
    - "test/support/datastore_example_rails_app/vendor/**/*"
    - "test/support/datastore_example_rails_app/Gemfile"
    - "vendor/**/*"

#################### Layout ##########################

Layout/LineLength:
  Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

##################### Lint ###########################

Lint/SendWithMixinArgument:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/cases/datastore_test.rb"
    - "test/cases/track_changes_test.rb"

#################### Style ###########################

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/IfWithBooleanLiteralBranches:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - "lib/active_model/datastore/carrier_wave_uploader.rb"

#################### Metrics #########################

Metrics/ModuleLength:
  CountComments: false
  Max: 150

Metrics/ClassLength:
  CountComments: false
  Max: 175
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - "test/**/*"

Metrics/AbcSize:
  Max: 26

#################### Naming ##########################

Naming/VariableNumber:
  Enabled: false
