source 'https://rubygems.org'

###########################################################################################
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end
# gem 'foo_bar', :github => 'foo/bar'
# Bundler would attempt to download the gem from https://github.com/foo/bar.git.
###########################################################################################

gem 'rails', '~> 5.1.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'

gem 'puma', '~> 3.9'
gem 'rack-timeout'

gem 'activemodel-datastore', path: File.expand_path('../../../..', __FILE__)

# Image storage
gem 'carrierwave', '~> 1.0'
gem 'mini_magick', '~> 4.7'
gem 'fog-google', '~> 0.6.0'
# Currently, fog-google does not support versions of google-api-client >= 0.9 or <= 0.8.5.
gem 'google-api-client', '>= 0.6.2', '< 0.9'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
  gem 'better_errors'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'faker'
  gem 'factory_bot_rails'
end
