source 'https://rubygems.org'
ruby File.read('.ruby-version').strip

###########################################################################################
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
# gem 'foo_bar', :github => 'foo/bar'
# Bundler would attempt to download the gem from https://github.com/foo/bar.git.
###########################################################################################

gem 'rails', '~> 6.1.4'
gem 'sass-rails', '>= 6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 5.0'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'

gem 'puma', '~> 5.0'
gem 'rack-timeout'

gem 'activemodel-datastore', path: File.expand_path('../../../..', __FILE__)

# Image storage
gem 'carrierwave', '~> 2.1'
gem 'mini_magick', '~> 4.7'
gem 'fog-google', '~> 1.11'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
  gem 'better_errors'
end

group :test do
  gem 'faker'
  gem 'factory_bot_rails'
end
